spring:
  application:
    name: dbgrupp
  datasource:
    url: jdbc:postgresql://localhost:5432/db_grupp
    username: postgres
    password: {$PG_PASSWORD}
  jpa:
    hibernate.ddl-auto: create
    properties.hibernate.format_sql: true
    hibernate.show-sql: true