spring:
  application:
    name: localhost
  datasource:
    url: jdbc:postgresql://localhost:5432/dbTest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create
    properties.hibernate.format_sql: true
    hibernate.show-sql: true